version: "3.9"

services:
  mini-bingo-app:
    build: .
    container_name: mini-bingo-app
    working_dir: /app
    stdin_open: true
    tty: true

    environment:
      PYTHONUNBUFFERED: "1"
      HISTORY_DIR: /app/data

    volumes:
      - ./data:/app/data
